// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package adobesigncommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.net.URLConnection;

public class JAVA_GetMimeType extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String FileName;

	public JAVA_GetMimeType(
		IContext context,
		java.lang.String _fileName
	)
	{
		super(context);
		this.FileName = _fileName;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return URLConnection.guessContentTypeFromName(this.FileName);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JAVA_GetMimeType";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
